import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import gradio as gr
from core.stress_agent import analyze_stress
from core.sleep_agent import analyze_sleep
from core.activity_agent import analyze_activity
from core.nutrition_agent import analyze_nutrition
from core.health_summary_agent import summarize_health
from core.anomaly_agent import detect_anomalies
from report.generate_health_report import generate_health_report

from simulate.generate_stress_data import generate_stress_samples
from simulate.generate_sleep_data import generate_sleep_samples
from simulate.generate_activity_data import generate_activity_samples
from simulate.generate_nutrition_data import generate_nutrition_sample

def run_health_agent_pipeline():
    # Step 1: Generate simulated data
    stress_data = generate_stress_samples(1)[0]
    sleep_data = generate_sleep_samples(1)[0]
    activity_data = generate_activity_samples(1)[0]
    nutrition_data = generate_nutrition_sample()

    # Step 2: Analyze using agents
    stress_result = analyze_stress(stress_data)
    sleep_result = analyze_sleep(sleep_data)
    activity_result = analyze_activity(activity_data)
    nutrition_result = analyze_nutrition(
        nutrition_data,
        stress_result,
        sleep_result,
        activity_result
    )

    # Step 3: Combine summary and anomaly detection
    summary_result = summarize_health(
        stress_result,
        sleep_result,
        activity_result
    )

    anomaly_result = detect_anomalies(
        stress_result,
        sleep_result,
        activity_result
    )

    # Step 4: Generate PDF report
    nutrition_macros = {
        "Protein": nutrition_data.get("protein", 0),
        "Carbs": nutrition_data.get("carbs", 0),
        "Fat": nutrition_data.get("fat", 0)
    }

    report_path = generate_health_report(
        stress_summary=stress_result,
        sleep_summary=sleep_result,
        activity_summary=activity_result,
        nutrition_summary=nutrition_result,
        nutrition_data=nutrition_macros
    )

    return (
        stress_result,
        sleep_result,
        activity_result,
        nutrition_result,
        summary_result,
        anomaly_result,
        report_path
    )

with gr.Blocks() as demo:
    gr.Markdown("# 📊 Wearable AI Health Report")
    gr.Markdown("This report is generated by autonomous AI agents based on simulated wearable sensor data.")

    generate_btn = gr.Button("🧠 Generate Report")

    stress_output = gr.Textbox(label="Stress Analysis")
    sleep_output = gr.Textbox(label="Sleep Analysis")
    activity_output = gr.Textbox(label="Activity Analysis")
    nutrition_output = gr.Textbox(label="Nutrition Advice")
    summary_output = gr.Textbox(label="📝 Health Summary")
    anomaly_output = gr.Textbox(label="🚨 Anomaly Detection")
    report_file = gr.File(label="📄 Download PDF Report")

    generate_btn.click(
        fn=run_health_agent_pipeline,
        inputs=[],
        outputs=[
            stress_output,
            sleep_output,
            activity_output,
            nutrition_output,
            summary_output,
            anomaly_output,
            report_file
        ]
    )

if __name__ == "__main__":
    demo.launch(share=True)
